--INSERT INTO POWER(ID,NAME) VALUES(1, 'Volar')
--INSERT INTO POWER(ID,NAME) VALUES(2, 'Invisibilidad')
--INSERT INTO POWER(ID,NAME) VALUES(3, 'Fuerza')
--INSERT INTO POWER(ID,NAME) VALUES(4, 'Fuego')
--INSERT INTO POWER(ID,NAME) VALUES(5, 'Velocidad')

INSERT INTO UNIVERSE VALUES(1, 'U001', 'Creado en 1939', 'Marvel')
INSERT INTO UNIVERSE VALUES(2, 'U002','Creado en 1934', 'DC')

INSERT INTO TYPE VALUES(1, 'T001', 'Heroe')
INSERT INTO TYPE VALUES(2, 'T002', 'Antiheroe')

INSERT INTO GENDER VALUES(1, 'G001', 'Hombre')
INSERT INTO GENDER VALUES(2, 'G002', 'Mujer')
